[package]
name = "image_combine"
version = "0.1.0"
edition = "2021"

[lib]
name = "image_combine"
crate-type = ["cdylib", "staticlib", "rlib"]
path = "src/lib.rs"

[dependencies]
flutter_rust_bridge = "=2.7.0"
image = "0.25.5"
rayon = "1.10.0"
mozjpeg = "0.10.12"