// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Merge multiple images vertically and return the result as JPEG bytes.
///
/// * `image_buffers` - A slice of byte vectors, each representing an image (e.g., PNG/JPEG).
///
/// Returns an `Option<Vec<u8>>` containing the JPEG-encoded bytes if successful,
/// or `None` if no images were loaded or encoding fails.
Future<Uint8List?> mergeImagesVertically(
        {required List<Uint8List> imageBuffers}) =>
    RustLib.instance.api
        .crateApiSimpleMergeImagesVertically(imageBuffers: imageBuffers);
