// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compress_to_jpeg_with_limit`

/// Merges multiple images vertically, then compresses the result using JPEG encoding.
/// An optional max size in KB can be specified.
///
/// * `image_buffers` - A list of byte vectors, each representing an image (PNG/JPEG, etc.).
/// * `max_size_kb` - Optional max size in KB. Attempts to stay within limit but not guaranteed.
///
/// Returns an `Option<Vec<u8>>` containing the compressed bytes if successful,
/// or `None` if loading/compressing fails.
Future<Uint8List?> mergeImagesVertically(
        {required List<Uint8List> imageBuffers, BigInt? maxSizeKb}) =>
    RustLib.instance.api.crateApiSimpleMergeImagesVertically(
        imageBuffers: imageBuffers, maxSizeKb: maxSizeKb);
